---
title: "Data Import"
output: github_document
---

```{r setup}
#option command i to insert a code chunk
library(tidyverse)
library(readxl) #read in excel
library(haven) #read in SAS
```

## Read in some data

Read in the litters dataset.
```{r}
#read in using relative path
litters_df = read_csv("./data/FAS_litters.csv") #use tab to auto complete
litters_df = janitor::clean_names(litters_df) #special notation so you don't have to load package- basically says in the janitor package use this function
```

## Take a look at the data

Printing in the console
```{r}
litters_df
```

```{r}
tail(litters_df)
```

```{r}
skimr::skim(litters_df)

#also View(litters_df) in console because it makes knitting difficult
```

## Options to read_csv
```{r}
litters_df = read_csv("./data/FAS_litters.csv", skip = 10, col_names = F)

litters_df = read_csv("./data/FAS_litters.csv", na = c("","NA",999)) #anytime it sees these three things will know it's supposed to be missing values

#check out the ?read_csv() for more info
```

## Other file formats

Read in an excel file.
```{r}
mlb_df = read_excel("./data/mlb11.xlsx") #use tab to auto complete
mlb_df

mlb_df_range = read_excel("./data/mlb11.xlsx", range = "A1:F7") #only certain cols
```

Read in a SAS file. 
```{r, eval=FALSE}
pulse_df = read_sas("./data/public_pulse_data.sas7bdat") #check back for update on how to do this- didn't work
pulse_df
```

